"""
Exporter
--------
Converts the final report string into downloadable formats.
- Markdown: trivial, just encode to bytes
- PDF: uses xhtml2pdf (pure Python, no GTK required)
"""
import io
import markdown as md_lib
from xhtml2pdf import pisa

def to_markdown_bytes(report: str, query: str) -> bytes:
    header = f"# Research Report\n**Query:** {query}\n\n---\n\n"
    return (header + report).encode("utf-8")

def _md_to_html(md: str, query: str) -> str:
    """Markdown → HTML conversion for PDF generation."""
    body = md_lib.markdown(md, extensions=["tables", "fenced_code", "toc"])
    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    @page {{
        size: letter;
        margin: 2cm;
    }}
    body {{
        font-family: Helvetica, Arial, sans-serif;
        color: #1a1a2e;
        line-height: 1.5;
    }}
    h1 {{ color: #4f46e5; font-size: 24pt; margin-bottom: 10pt; }}
    h2 {{ color: #374151; font-size: 18pt; margin-top: 20pt; border-bottom: 1px solid #eee; }}
    h3 {{ color: #4b5563; font-size: 14pt; margin-top: 15pt; }}
    p {{ margin-bottom: 10pt; }}
    li {{ margin-bottom: 5pt; }}
    code {{ background-color: #f3f4f6; font-family: Courier, monospace; }}
    .query-badge {{
        background-color: #ede9fe;
        color: #4f46e5;
        padding: 5pt 10pt;
        font-size: 10pt;
        margin-bottom: 20pt;
    }}
    .footer {{
        text-align: center;
        font-size: 9pt;
        color: #9ca3af;
        margin-top: 50pt;
    }}
</style>
</head>
<body>
    <div class="query-badge">Research Topic: {query}</div>
    {body}
    <div class="footer">Generated by Research Agent</div>
</body>
</html>"""

def to_pdf_bytes(report: str, query: str) -> bytes:
    """
    Generate PDF using xhtml2pdf. 
    This is a pure-python solution that does not require GTK.
    """
    html = _md_to_html(report, query)
    result = io.BytesIO()
    
    # Create PDF
    pdf = pisa.pisaDocument(io.BytesIO(html.encode("utf-8")), result)
    
    if not pdf.err:
        return result.getvalue()
    else:
        raise RuntimeError(f"PDF generation failed with {pdf.err} errors")
